{
    # TODO: Configure this to use only the needed kernel modules
    # Start the rest with a systemd unit after boot

    # Generic boot process config
    boot = {
        # Bootloader config
        loader = {
            # Where the EFI system partition is mounted
            efi.efiSysMountPoint = "/boot";

            # Systemd-boot config
            systemd-boot = {
                enable = true;
                editor = false;
                extraInstallCommands = ''
echo "default @saved
timeout 3
console-mode max" > /boot/loader/loader.conf'';
            };
        };

        # Enables NTFS support for mounting
        supportedFilesystems = [ "ntfs-3g" ];

        # Sets up a kernel that boots on crash to save crash logs etc
        crashDump.enable = true;

        # Sets the console log level to 0 for a silent boot
        consoleLogLevel = 0;

        # Removes mandatory messages generated by nixOS scripts
        initrd.verbose = false;
    };
}